/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'ericmash' at '03/07/16 8:13 PM' with Gradle 2.14
 *
 * @author ericmash, @date 03/07/16 8:13 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
